# Excercises for Day 3

## 1. Numpy exercises

In [1]:
import numpy as np

#### a.

In [4]:
vec_a = np.zeros(10)
vec_a[4] = 1
print(vec_a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### b.

In [5]:
vec_b1 = np.arange(50)
vec_b2 = vec_b1 > 9
vec_b3 = vec_b1[vec_b2]

print(vec_b1)
print(vec_b2)
print(vec_b3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[False False False False False False False False False False  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### c.

In [7]:
vec_c = np.flip(vec_b3)
print(vec_c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### d.

In [8]:
vec_d = np.arange(9).reshape(3,3)
print(vec_d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### e.

In [31]:
vec_e1 = np.array([1,2,0,0,4,0])
vec_e2 = vec_e1 != 0

vec_e3 = np.where(vec_e1[vec_e2])[0]
print("Indices of non-zero elements: ")
print(vec_e3)

Indices of non-zero elements: 
[0 1 2]


#### f.

In [46]:
vec_f = np.random.random(30)

mean_f = np.mean(vec_f1)
print(mean_f)

0.4731354715658801


#### g.

In [70]:
n=10
mat_g = np.zeros(n**2).reshape(n,n)

for i in np.arange(n):
    mat_g[i,0] = 1
    mat_g[i,n-1] = 1

for j in np.arange(n):
    mat_g[0,j] = 1
    mat_g[n-1,j] = 1

print(mat_g)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### h.

In [83]:
mat_h1 = np.zeros(64)

x = 0
while x in np.arange(64):
    mat_h1[x] = 1
    x += 2

mat_h2 = np.reshape(mat_h1, (8,8))
print(mat_h2)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### i.

In [85]:
A = np.array([1,0])
val1 = 8
val2 = 4
rep = (val1,val2)
mat_i = np.tile(A,rep)
print(mat_i)

[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


#### j.

In [90]:
Z = np.arange(11)
i = np.array([4,5,6,7])
Z[i] = -Z[i]
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### k.

In [115]:
Z = np.random.random(10)

print("Original vector:")
print(Z)
print("")

for x in np.arange(1,10):
    for y in np.arange(x,0,-1):
        if Z[y] < Z[y-1]:
            a = Z[y-1]
            Z[y-1] = Z[y]
            Z[y] = a

print("Sorted vector:")
print(Z)

Original vector:
[0.47260591 0.18239814 0.85139514 0.65062194 0.27609058 0.03732087
 0.39478453 0.78009611 0.34485584 0.1809211 ]

Sorted vector:
[0.03732087 0.1809211  0.18239814 0.27609058 0.34485584 0.39478453
 0.47260591 0.65062194 0.78009611 0.85139514]


#### l.

In [122]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

equal = np.array_equal(A,B)
print(equal)


True


#### m.

In [142]:
Z = np.arange(10, dtype=np.int32)
print(Z.dtype)

Z = np.float32(Z)
print(Z.dtype)

int32
float32


#### n.

In [147]:
A = np.arange(9).reshape(3,3)
print(A)

B = A + 1
print(B)

C = np.dot(A,B)
print(C)

D = np.zeros(3)
for i in np.arange(3):
    for j in np.arange(3):
        if i == j:
            D[i] = C[i][j]

print(D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 18  21  24]
 [ 54  66  78]
 [ 90 111 132]]
[0. 0. 0.]
[ 18.  66. 132.]


## 2. Speed optimization using Numpy

See solution for exercises of Day 2.

## 3. Examples on classes and inheritance in Python

In [201]:
class Person(object):
    def __init__(self, first, last):
        self.first = first
        self.last = last

class Student(Person):
    def __init__(self, first, last, subject):
        Person.__init__(self, first, last)
        self.subject = subject
        
class Teacher(Person):
    def __init__(self, first, last, course):
        Person.__init__(self, first, last)
        self.course = course

def printNameSubject(first,last,subject):
    newpers = Student(first,last,subject)
    print("Student: %s %s, %s" % (first, last, subject))
    
def printNameCourse(first,last,course):
    newpers = Teacher(first,last,course)
    print("Teacher: %s %s, %s" % (first, last, course))


printNameSubject("First", "Last", "Subject")
printNameCourse("First", "Last", "Course")

Student: First Last, Subject
Teacher: First Last, Course
